### ISSUE TITLE
HDMI input recognized as TV input, but black screen

### ISSUE THREAD

**Issue by RianBeck** [zwenergy/gbaHD#6]
The latest build as available on the google drive of Mogi_codemasterv works on my external computer monitor, however, I get a black screen in my panasonic viera tv (2014 model). I have tried older builds as well, but those don't even get recognized by the tv at all. On the latest build the tv does recognize the aspect ratio (16:9). 

Would be very much appreciated if this could be fixed, as I would love to play on my tv, thanks!

**Comment by Bertuga** [comment]
This is an issue with the TV. The gbaHD frequency is the same as the GBA which is not 60fps (it is something close to 59.72), a lot of TVs won't accept an irregular frame rate as this one. I'm also an viera owner (older model than yours) and it doesn't work as well, but it is the price to have it working as close as possible as the original hardware. 

The GBA consolizer actually works at a 60fps, but the collateral effect of this is that everything runs slightly faster. Maybe it would be possible to implement this "60fps" mode to the gbaHD project, since the consolizer runs in an older fpga thant the gbaHD, to work as a compatibility mode for all TVs (the gba consolizer has two separate firmwares, to run at the original fps or the 60fps). I'm leaving this just as an suggestion, the project is amazing and I couldn't possibly ask for more.

**Comment by RianBeck** [comment]
Thanks a lot for the explanation! Makes a lot more sense now. Indeed a 60Hz option would definitely be a nice to have, but as you say, amazing project, and I love it either way!

**Comment by RianBeck** [comment]
The latest update has made the gbaHD compatible with my tv, thanks a lot for the great work!
